### ISSUE TITLE
चकामः prakriya is not loading

### ISSUE THREAD

**Issue by vshylaja** [drdhaval2785/prakriya#108]
https://ashtadhyayi.com/dhatu/01.0892?form=%E0%A4%9A%E0%A4%95%E0%A4%A4%E0%A4%BF
०१.०८९२ चक्
चकामः prakriya is not loading
Please check other forms also in this page.

**Comment by drdhaval2785** [comment]
Seems to be a rendering issue on part of ashtadhyayi.com website.
The API seems to be correctly working. I checked up in the console.
Call to https://api.sanskritworld.in/v0.0.2/verbforms/devanagari/%E0%A4%9A%E0%A4%95%E0%A4%BE%E0%A4%AE%E0%A4%83?output_transliteration=devanagari returns correct output.
@neeleshb may like to check up the javascript which is rendering it ion ashtadhyayi.com.

**Comment by neeleshb** [comment]
Dhatupatha has 2 चक् dhatus. On the website, these are present at 1.98 and
1.892. In the धातुरूपनन्दिनी book, they are resp. No. 93 and 783.
The link that you pointed to maps to Dhatu number 1.98 (I use the same
numbering as you, so this is 1.98 in your JSON).
That dhatu, however, is aatmanepadi as per my database.  I verified it
using the JNU link present in your json output. You might want to cross
check your references / links and fix the forms if needed.

The other dhatu, which this bug talks about, is 1.892. It is Parasmaipadi,
and it seems to be missing from your system. At least the API does not
return it.

The API call that I am doing is this (Seems to be same as what you quoted).
https://api.sanskritworld.in/v0.0.2/verbforms/devanagari/%E0%A4%9A%E0%A4%95%E0%A4%BE%E0%A4%AE%E0%A4%83?output_transliteration=devanagari

Is there 1.892 in your system? If not, you can just renumber the current
dhatu to 1.892 and everything will start working.

**Comment by drdhaval2785** [comment]
That means you are checking for verb number from the API output on your side. If it matches, then only it is shown to the user.
Is that correct understanding on my part?

**Comment by drdhaval2785** [comment]
There are two dhatus.
1. च॑कँ॑ - तृप्तौ, भ्वादि 01.0098 
2. च॑कँ॒ - तृप्तौ प्रतिघाते च, भ्वादि 01.0892

https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/dhaatupaatha/files-6-9-2014/mA483.html for 1 shows that this dhatu is parasmaipadi
 and
https://www.sanskritworld.in/sanskrittool/SanskritVerb/Data/dhaatupaatha/files-6-9-2014/mA72.html for 2 shows that this dhatu is Atmanepadi.

**Comment by neeleshb** [comment]
Yes, I am checking the numbers returned in the result and displaying the
results only when numbers match.

The 98 verb in my system is "चक तृप्तौ प्रतिघाते च". In your system it
seems to be चक तृप्तौ । The 892 verb in my system is "चक तृप्तौ" . In your
system it seems to be चक तृप्तौ प्रतिघाते च ।
And I am checking the numbers along with Pada-Vachana etc. Hence even
though I am getting the result I am not displaying it

Unfortunately I cannot reverse or change the numbers on ashtadhyayi.com
now, because the number is shown as part of the URL and the URL is
potentially copy-pasted by multiple users in their work.

I can try avoiding the check on the numbers, but that might cause a few
more issues (I am sure I must have come across some issues and that's why I
added the numeric check, but I don't remember them now).

The last possible way is to add another column in my db to represent your
numbers and then check on that. May be that will solve all such problems.

I notice that you have added me to 5+ more similar bugs, all these appear
to be due to numeric check.

**Comment by drdhaval2785** [comment]
>The last possible way is to add another column in my db to represent your numbers and then check on that. May be that will solve all such problems.

It seems to be the most sane idea. Kindly do it as soon as possible. Otherwise there would be too many false alarms by @vshylaja.

**Comment by neeleshb** [comment]
sounds good.  I will also request her not to file bugs on your side without
checking that the prakriya does not load on your side as well.

**Comment by vshylaja** [comment]
Yes. Now I am checking and filing an issue (for new errors) only if it also fails to load at
https://avinashvarna.github.io/prakriya/

Also closed some past issues, if it loaded at your side and only fails on astadhyayi.com

**Comment by drdhaval2785** [comment]
https://ambuda-org.github.io/vidyullekha/?dhatu=01.0892&tab=tin handles it.
