### ISSUE TITLE
help needed with packaging

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/prakriya#26]
I am in the following situation.
There is a 70 MB tar.gz file which contains all the necessary verb form data. When extracted, it comes to arount 1.1 GB.

For creating a python package, I have two options
1. Use API - It avoids downloading tons to the user side, but it seems a slow and not so efficient implementation.
2. Download data 

For point 2, I have a few questions to ask as this is my first python package.
1. How do I ensure that the file of interest i.e. https://github.com/drdhaval2785/prakriya/releases/download/v0.0.2/derivation_v003.tar.gz gets downloaded after the code is downloaded?
2. How do I extract the data from tar.gz file when it gets downloaded?

I know of shell scripts which can be run, but I don't think it is the preferred way of doing it in pip.

**Comment by drdhaval2785** [comment]
@vvasuki, @avinashvarna or @kamadathil any suggestions?

**Comment by avinashvarna** [comment]
My thoughts:
> How do I ensure that the file of interest i.e. https://github.com/drdhaval2785/prakriya/releases/download/v0.0.2/derivation_v003.tar.gz gets downloaded after the code is downloaded?

In the sanskrit_parser project, we've been using a lazy-download technique. When the object that needs the data is created, it checks if the data exists on the file system, and if not, downloads it. Take a look at the code in `__init__` and the `_get_files` functions [here](https://github.com/kmadathil/sanskrit_parser/blob/master/sanskrit_parser/util/inriaxmlwrapper.py)

However, it may be simpler and preferable to have the data bundled into the package itself. Setuptools and the like support it by exposing a [simple option](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files) in the setup.py call. I would recommend using this approach since it is only 70MB of data.

> How do I extract the data from tar.gz file when it gets downloaded?

1. If the goal is to extract all data at once, a similar approach could be used in the `__init__`  to check if the data has been extracted and if not extract the required files.
2. If we do not want to use 1.1GB of space on the user's disk, we can dynamically read out only the required file using https://docs.python.org/2/library/tarfile.html?highlight=gzip#tarfile.TarFile.extractfile This may be slightly slower but more space efficient.

Let me know if you need any help implementing these.

**Comment by vvasuki** [comment]
उचितमुक्तम् अविनाशेन। https://github.com/drdhaval2785/prakriya/issues/4#issuecomment-353125931 इत्यप्यवधेयम्।

**Comment by vvasuki** [comment]
Here's an idea which can kill 3 birds in one stone. Make a babylon dict, and use https://github.com/lig/pystardict/blob/master/pystardict.py . Read using the pystardict interface, replace <BR> with \n and serve. You get O(1) time reads.

The 3 birds:
- The current API.
- Making a babylon dict.
- Exemplify a dict based py library for others to copy and apply to the many other useful dicts out there.

**Comment by avinashvarna** [comment]
But is it NoSQL compliant ;-)?

**Comment by avinashvarna** [comment]
@drdhaval2785, Are you working on this? If not, I can try my hand in the weekend. At least the basic python package version. Since the data is not natively in the babylon format, we would have to convert it, which would require a separate script anyway. So is there enough value in choosing that as the distribution format for the package as well? We can take that up later.

**Comment by drdhaval2785** [comment]
I am trying it today. If I fail, will pass the buck to you for weekend. I
am trying to learn packaging. So trying my hand on this.

**Comment by drdhaval2785** [comment]
package launched successfully.
https://prakriya.readthedocs.io/en/latest/usage.html for the instructions.
`pip install prakriya`

**Comment by drdhaval2785** [comment]
@avinashvarna and @vvasuki 
Please use and give feedback. Also feel free to do a PR at https://github.com/drdhaval2785/python-prakriya
