### ISSUE TITLE
link to AS commentaries

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/prakriya#31]
https://github.com/drdhaval2785/prakriya/issues/30#issuecomment-355792305

**Comment by vvasuki** [comment]
Is there real benefit in benefit of doing this in the json output? 

Not really - one can long press or right click to see commentaries in stardict-clients, and one can link to the appropriate ashtadhyayi.com page in @avinashvarna 's UI.

Is there a problem with doing this in the json output?

Yes - It makes it less concise and uglier.

**Comment by drdhaval2785** [comment]
I gave it a thought. It indeed will be ugly. Let us keep it for jvascript
to handle.

http://ashtadhyayi.com/sutraani/{adhyaya}/{pada}/{sutra} is the format. It
should be possible for javascript to handle this. I vote for link rather
than long press.

**Comment by vvasuki** [comment]
>‌  http://ashtadhyayi.com/sutraani/{adhyaya}/{pada}/{sutra} is the format. It should be possible for javascript to handle this. I vote for link rather than long press.

साधु। अविनाशजालपुटे link इत्येव भवति। long press इति stardict कोशय् उक्तम् (तत्र link स्थापनम् इतोऽपि प्रयत्नम् अपेक्षते - यदि तत्राप्य् अविनाश उत्सुकः, ओमित्येवाहं ब्रुवे)।

**Comment by avinashvarna** [comment]
Are the sutra numbers consistent with ashtadhyayi.com? If so, adding the link in the UI will be simple enough.

**Comment by vvasuki** [comment]
अधुनैव नीलेशाद् वार्तान्तरे सम्भाष्यमाणाद् +इत्थम् अपृच्छम् - 


*‌ तव जालक्षेत्रम् महतः प्रयोजनायास्त्यन्यत्रापि, यथा - https://github.com/drdhaval2785/prakriya/issues/31#issuecomment-355794065 । अपि किमपि REST API प्रकाशयेः? तेन यथेष्टरीत्या जालक्षेत्रान्तरेषु दर्शनं सरलतरम् भवति।

*‌तव github नाम किम्?

**Comment by avinashvarna** [comment]
तदर्थं stardict files वर्तन्ते खलु ? वेदवापी couch db मध्ये तानि स्थाप्यन्ते चेत् REST API स्वयं सिद्धं न भवेत् किम् ?

**Comment by vvasuki** [comment]
>‌ तदर्थं stardict files वर्तन्ते खलु ? वेदवापी couch db मध्ये तानि स्थाप्यन्ते चेत् REST API स्वयं सिद्धं न भवेत् किम् ?

सत्यम् - किञ्च शङ्के तत्रास्य सज्जनस्याधिकतरेण श्रमेण परिष्कृतपाठस् तत्रैव सुलभस् स्यादिति। पुरा मया 

>‌  कथं शोधनानि त्वत्कृतानि वा ऽन्यकृतानि वा परस्परोपयोगाय कल्पयेमेति। ​How about creating a "canonical source" for every commentary and making all corrections there? For siddhAnta-kaumudI, dhaval's repo could be it. For most of the rest, we can just clone and fork off ​
https://github.com/aupasana/ashtadhyayi since we've not heard from ajit.

इति सूचितम्। किञ्च न ततः किञ्चित् फलितम्।

**Comment by drdhaval2785** [comment]
> Are the sutra numbers consistent with ashtadhyayi.com? 

Mostly yes. And even if it doesn't agree completely, the site has a convenoent way to go to next and previous sutra number. And from my experience the difference will be one or two sutra numbers only. So assuming that the sutra numners are consistent is a reasonable assumption to start with.

When time permits, will try to find differences programmatically.

**Comment by drdhaval2785** [comment]
> we can just clone and fork off ​

I did so and also corrected some errors too. https://github.com/drdhaval2785/ashtadhyayi

**Comment by neeleshb** [comment]
Namaste,

JSON api - www.ashtadhyayi.com/sutraani/json.php/1/1/1

Please note that I am actively working on rectifying the errors in the commentaries (and also writing my own commentary) for all sutras. The content is changing almost every day, and thus at least for now,  please don't fetch and store the data locally - your content will definitely be stale. Instead, try to pull up data live when the user visits your page.

Also, I know a github repo might be better for sharing the content; but  at this stage, the database behind ashtadhyayi.com is the only source of truth for the website and I plan to continue that way for quite some time - because that's the easiest way to pull up the latest data and render it on the website. Anybody and everybody is welcome to directly link to the website or to use the  API to distribute the content. 

-Neelesh

**Comment by vvasuki** [comment]
>‌ I plan to continue that way for quite some time - because that's the easiest way to pull up the latest data and render it on the website.

Thanks, @neeleshb .  This is good given that the rest of us are presumably not as active correcting texts - On the other hand, this might benefit from some further consideration. Imagine dumping all info in json files; and imagine your frontend reading https://raw.githubusercontent.com/ashtadhyayi-data/001_001_003.json using javascript and serving it to the user in an attractive way. This change is actually simple to effect and wont affect efficiency, and will get you and us the following benefits:

- Faster corrections! You'll get pull requests and have less sweat.
- Folks can get a full dump fast (just clone the repo).

**Comment by drdhaval2785** [comment]
I also back the suggestion of @vvasuki. It will make data more accessibe
and amenable to PRs. I extensively worked in Cologne dictionary
corrections, so I have some experience in programatic data cleaning. But as
the PRs on aupasana repository did not get through, I left it in between.
If the repo is responsive, I would love to chip in.

**Comment by drdhaval2785** [comment]
@neeleshb
https://github.com/aupasana/ashtadhyayi/issues/9 is the closest candidate for correction.

**Comment by avinashvarna** [comment]
Original issue (links to ashtadhyayi.com) added in latest version of UI.

**Comment by drdhaval2785** [comment]
Open in new tab is required.

**Comment by gasyoun** [comment]
> link to the appropriate ashtadhyayi.com

Don't we want to make a local copy of the site? When it will die, such a gem will get lost.

> The content is changing almost every day

Is there a changelog that one can follow?

> I extensively worked in Cologne dictionary
corrections, so I have some experience in programatic data cleaning

Yes! But no in the past - in the future as well, Dhaval :calendar:

**Comment by neeleshb** [comment]
Answering some of the questions raised by @drdhaval2785, @vvasuki and @gasyoun, also giving some background. 

1.  The data powering ashtadhyayi.com was first pulled up from Dr. Dhaval's and aupasana's github repositories around a year ago, and I have formatted it extensively to (a) fix multiple errors, and (b) add markups specifically to support formatting in the UI. I believe the data is probably cleaner than existing repositories around, but I could very well be wrong here - because I haven't tracked the original repositories since then. 

2. At this stage, the corrections being done on ashtadhyayi.com are completely manual (looking in the book and correcting the data) and there is no programmatic stuff going on at all.  Most of the edits involve fixing typos / adding missing sentences and primarily adding my own commentary for all sutras in simple Sanskrit (which is in fact the fundamental motivation behind creating the website). There is no changelog maintained for this. 

3. The site (data + website scripts) has regular daily backups, but they are stored only locally on my machine and at one/two places the cloud. Not on github.

4. I do agree that an active github repository is definitely a better way to collaborate. However, given limited time at hand and with other developments on ashtadhyayi.com in pipeline (for example - I just added a [full-commentaries search](http://ashtadhyayi.com/sutraani/search.php) on the website), I won't have cycles for that. 

4. As I clarified earlier, at least for now - I plan to continue doing edits on ashtadhyayi.com directly, because my system is very well set up for those and making changes to the system is not something I would like to take up at this stage. Sometime in the future, hopefully. 

5. Finally, if anyone is interested in creating a repository hosting the content of ashtadhyayi.com, they can certainly use the available JSON API. I can also tune the API if needed.

Thanks
Neelesh

**Comment by vvasuki** [comment]
Thanks for clarifying @neeleshb - your hard focus on your priorities is perfectly reasonable. The full commentary search is beautiful ! I am not a php programmer, but I am curious how you're doing it. More generally, would you mind hosting your code repository on github? Though you don't have the cycles to change the well-oiled system, there is the possibility that someone else might do it for you with a PR. In any case, it would be quite satisfying (and potentially inspiring) for curious onlookers  like me.

**Comment by vvasuki** [comment]
Following up on https://github.com/drdhaval2785/prakriya/issues/31#issuecomment-356158348 by @neeleshb - I've created https://github.com/sanskrit-coders/ashtadhyayi-dump to use the API to dump data from ashtadhyayi.com - @drdhaval2785 and @avinashvarna already have admin access, and @neeleshb has been invited with similar permissions (It would help to track requests and discussions in separate threads there by assigning to @neeleshb as needed) . I've requested a couple of minor changes to the API and its output.

**Comment by avinashvarna** [comment]
> Open in new tab is required.

Done

**Comment by drdhaval2785** [comment]
> There is no changelog maintained for this.
For short run, this is fine, but for long run we need changelog. https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/correctionform.txt, https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/history.txt and https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/cfr.tsv may help get some idea / format for changelog.

**Comment by drdhaval2785** [comment]
> Finally, if anyone is interested in creating a repository hosting the content of ashtadhyayi.com, they can certainly use the available JSON API. I can also tune the API if needed.

You corrected five lines. I corrected some on my copy. I submit the corrections to you. How will you handle these conflicts?
git has established conflict management implementations. Let us piggyback on it.

**Comment by drdhaval2785** [comment]
The discussion regarding ashtadhyayi.com and its dump and JSON API is separately ongoing at ashtadhyayi-dump repository created by vvasuki.
Closing this.
Link to AS is done in UI.

**Comment by vvasuki** [comment]
Oops. I just deleted the ashtadhyayi-dump repo and lost the issues. The dump has actually happened elsewhere though - https://github.com/ashtadhyayi/ashtadhyayi_org_data .

तथा ऽस्माकमस्ति नूतनोद्यमो ऽत्र प्रासङ्गिकः - https://github.com/sanskrit/ashtadhyayi https://ashtadhyayi.github.io/ui/about/ ।
